source 'http://rubygems.org'
gem 'liquid', '2.2.2'
gem 'redcarpet'
gem 'pygments.rb'
gem 'exifr'
gem 'rakuten'
gem 'guard', '1.0.1'
gem 'guard-shell', '0.4.0'
gem 'guard-livereload', '0.4.2'
gem 'thor'
gem 'nebel', :git => 'git://github.com/mizzy/nebel.git'
